name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        source venv/bin/activate
        flake8 .
    - name: Check import sorting with isort
      run: |
        source venv/bin/activate
        isort . --check-only
    - name: Check code formatting with black
      run: |
        source venv/bin/activate
        black . --check
    - name: Type check with mypy
      run: |
        source venv/bin/activate
        mypy .

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Run tests
      run: |
        source venv/bin/activate
        pytest
[flake8]
exclude = venv
max-line-length = 88
